# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: Face Maulers
repo_url: https://github.com/clux/campaign
repo_name: clux/campaign
edit_uri: edit/main/docs
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  faviocon: favicon.jpg
  palette:
  - scheme: slate
    accent: amber
    primary: black
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: default
    media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
nav:
- Campaign: index.md
- PCs:
  - pcs/mordai.md
  - pcs/goatweaver.md
  - pcs/faey.md
  - pcs/hjarka.md
  - pcs/pendle.md
  - pcs/hanir.md
  - pcs/dhoznak.md
  - pcs/zed.md
  - pcs/iz.md
  - pcs/bron.md
  - pcs/windsorrow.md
  - pcs/arqarin.md
  - pcs/jendn.md
  - pcs/andraste.md
  - pcs/chipgrin.md
  - pcs/tyshdille.md
- NPCs:
  - npcs/adalon.md
  - npcs/almah.md
  - npcs/andariel.md
  - npcs/anjanu.md
  - npcs/arklem.md
  - npcs/beniago.md
  - npcs/berchta.md
  - npcs/cameron.md
  - npcs/celerom.md
  - npcs/dessirris.md
  - npcs/dhaikhezzish.md
  - npcs/diana.md
  - npcs/diggermattocks.md
  - npcs/felgolos.md
  - npcs/galeron.md
  - npcs/gregor.md
  - npcs/gurnik.md
  - npcs/gwyn.md
  - npcs/hergatha.md
  - npcs/ilvara.md
  - npcs/irae.md
  - npcs/jarlaxle.md
  - npcs/kazook.md
  - npcs/kenny.md
  - npcs/koth.md
  - npcs/larloch.md
  - npcs/malexis.md
  - npcs/meepo.md
  - npcs/mordai-vell.md
  - npcs/paxos.md
  - npcs/rak-tulkhesh.md
  - npcs/sansuri.md
  - npcs/silth.md
  - npcs/skipper.md
  - npcs/sydney.md
  - npcs/thoggi.md
  - npcs/travok.md
  - npcs/umnos.md
  - npcs/ursula.md
  - npcs/valindra.md
  - npcs/vanquesh.md
  - npcs/virgil.md
  - npcs/zaehesh.md
- Deities:
  - deities/pantheon.md
  - deities/dahaka.md
  - deities/demogorgon.md
  - deities/eilistraee.md
  - deities/kavaki.md
  - deities/kiaransalee.md
  - deities/kraken.md
  - deities/lolth.md
  - deities/orcus.md
  - deities/ravenqueen.md
  - deities/seelie-court.md
  - deities/selune.md
  - deities/umberlee.md
  - deities/xial.md
- Rules:
  - rules/calendar.md
  - rules/chronomancy.md
  - rules/combat.md
  - rules/dungeons.md
  - rules/economics.md
  - rules/factions.md
  - rules/generators.md
  - rules/house.md
  - rules/loot.md
  - rules/maps.md
  - rules/music.md
  - rules/nerfs.md
  - rules/npcs.md
  - rules/politics.md
  - rules/punishment.md
  - rules/recreation.md
  - rules/retrospective.md
  - rules/shopping.md
- Factions:
  - factions/arcane-brotherhood.md
  - factions/bregan-daerthe.md
  - factions/graycloaks.md
  - factions/mages-guild.md
  - factions/silver-helix.md
  - factions/sunset-warriors.md
  - factions/undying-soul.md
- Planar:
  - planar/argentil-peak.md
  - planar/argentil-simulator.md
  - planar/cania.md
  - planar/cityofbrass.md
  - planar/feywild.md
  - planar/gehenna.md
  - planar/maerimydra.md
  - planar/morgolondar.md
  - planar/ormolu-complex.md
  - planar/penthacoron.md
  - planar/shadowfell.md
  - planar/tesseract.md
  - planar/ysgard.md
- Sword Coast:
  - coast/waterdeep.md
  - coast/sunless-citadel.md
  - coast/oakhurst.md
  - coast/baldursgate.md
  - coast/candlekeep.md
  - coast/cursed-grove.md
  - coast/docks.md
  - coast/rulers.md
  - coast/undermountain.md
  - coast/wd-demogorgon.md
  - coast/yawning-portal.md
- Underdark:
  - underdark/velkynvelve.md
  - underdark/sloobludop.md
  - underdark/neverlight.md
  - underdark/blingdenstone.md
  - underdark/blingdenstone-justice-pit.md
  - underdark/blingdenstone-rockblight.md
  - underdark/darklake.md
  - underdark/atishalla.md
  - underdark/solas-domain.md
  - underdark/lirthuqos-lair.md
  - underdark/telnarquel.md
  - underdark/kruthik-lair.md
  - underdark/gracklstugh.md
  - underdark/menzo.md
  - underdark/spider-cavern.md
- Escape:
  - whiteplume/evermoors.md
  - whiteplume/plume.md
  - whiteplume/plume-escape.md
  - whiteplume/plume-left.md
  - whiteplume/plume-right.md
  - whiteplume/goat-village.md
  - whiteplume/kobold-lair.md
- Sea:
  - seaofbones/artemis.md
  - seaofbones/devils-reef.md
  - seaofbones/empress.md
  - seaofbones/firewatch-island.md
  - seaofbones/grundsgryn.md
  - seaofbones/mirror-temple.md
  - seaofbones/moray.md
  - seaofbones/piracy.md
  - seaofbones/ruathym.md
  - seaofbones/trench-of-darkness.md
- North:
  - north/luskan.md
  - north/neverwinter.md
  - north/neverwinter-end-battle.md
  - north/boreal-valley.md
  - north/castle-never.md
  - north/castle-nowhere.md
  - north/evernight.md
  - north/icewind-dale.md
  - north/mirabar.md
  - north/toll-trolls.md
  - north/yeenoghus-lair.md
  - spine/stormguard-citadel.md
  - spine/gilgrin-vault.md
  - spine/gilgrin.md
  - spine/halos-2.md
  - spine/halos-3.md
  - spine/halos.md
  - spine/protectorate.md
  - spine/rimehaze.md
- East:
  - east/acropolis.md
  - east/bonecity.md
  - east/dragonlake-pier.md
  - east/epilogue.md
  - east/ideas.md
  - east/irithyll-oubliette.md
  - east/irithyll.md
  - east/nekrina.md
  - east/path-of-suffering.md
  - east/velddrinnsshar.md
- Recaps:
  - recaps/00-introduction.md
  - recaps/01-waterdeep-start.md
  - recaps/02-sunken-citadel.md
  - recaps/03-cursed-grove.md
  - recaps/04-waterdeep-shopping.md
  - recaps/05-velkynvelve.md
  - recaps/06-oozing-temple.md
  - recaps/07-sloobludop-ritual.md
  - recaps/08-darklake-spectator.md
  - recaps/09-neverlight-spores.md
  - recaps/10-kruthik-dungeon.md
  - recaps/11-queen-and-spiders.md
  - recaps/12-blingdenstone-taps.md
  - recaps/13-rockblight.md
  - recaps/14-pit-of-justice.md
  - recaps/15-battle-for-blingdenstone.md
  - recaps/16-puzzling-devils.md
  - recaps/17-infernal-trials.md
  - recaps/18-infernal-gary.md
  - recaps/19-mizzrym.md
  - recaps/20-surface.md
  - recaps/21-monastic-teachings.md
  - recaps/22-waving-crab.md
  - recaps/23-three-way-charms.md
  - recaps/24-inverting-the-ziggurat.md
  - recaps/25-sphinxen-clues.md
  - recaps/26-blood-and-beef.md
  - recaps/27-inner-city-questing.md
  - recaps/28-abandoned-umberlee.md
  - recaps/29-chaotic-pendle.md
  - recaps/30-mammond.md
  - recaps/31-story-of-kenny.md
  - recaps/32-stranded-on-moray.md
  - recaps/33-mirror-hans.md
  - recaps/34-tyrant-deception.md
  - recaps/35-temple-of-the-queen.md
  - recaps/36-grundsgryn.md
  - recaps/37-day-of-the-androsphinx.md
  - recaps/38-iz-ship.md
  - recaps/39-sinking-octopus.md
  - recaps/40-lighthouse-penetration.md
  - recaps/41-firewatch-night.md
  - recaps/42-reefer-seagull.md
  - recaps/43-shipnanigans.md
  - recaps/44-under-pressure.md
  - recaps/45-maerimydra.md
  - recaps/46-neverwinter-redshirt.md
  - recaps/47-never-gnoll.md
  - recaps/48-fireforge.md
  - recaps/49-crusher.md
  - recaps/50-nowhere.md
  - recaps/51-cloaks-and-pugs.md
  - recaps/52-orphans-and-cages.md
  - recaps/53-wish-unleashed.md
  - recaps/54-scenic-luskan.md
  - recaps/55-brotherhood.md
  - recaps/56-drinking-culture.md
  - recaps/57-mirabar.md
  - recaps/58-hill-giant-hotel.md
  - recaps/59-undercover-chads.md
  - recaps/60-turtle-shift.md
  - recaps/61-seer-planning.md
  - recaps/62-hazy-bracers.md
  - recaps/63-rime-turtles.md
  - recaps/64-protectorate.md
  - recaps/65-key-exchange.md
  - recaps/66-gilgrinvault.md
  - recaps/67-felgy.md
  - recaps/68-goryms-egg.md
  - recaps/69-vault-unseal.md
  - recaps/70-waterdeep.md
  - recaps/71-sharios-tomb.md
  - recaps/72-prince-of-demons.md
  - recaps/73-demo-gone-gone.md
  - recaps/74-aggressive-protection.md
  - recaps/75-grymin-wrecks.md
  - recaps/76-five-giants.md
  - recaps/77-serissas-heart.md
  - recaps/78-halos-labyrinth.md
  - recaps/79-neri-bows.md
  - recaps/80-plutocracy.md
  - recaps/81-fracto-nimbuli.md
  - recaps/82-tree-to-kavaki.md
  - recaps/83-going-east.md
  - recaps/84-chief-bonehead.md
  - recaps/85-circle-of-zaehesh.md
  - recaps/86-oblexian-dig.md
  - recaps/87-pask-luskan.md
  - recaps/88-argentil-headcount.md
  - recaps/89-argentil-mages.md
  - recaps/90-undead-diplomacy.md
  - recaps/91-kavaki-variety.md
  - recaps/92-old-witch.md
  - recaps/93-tentacley-mine.md
  - recaps/94-akkhan-drill.md
  - recaps/95-past-akkhan.md
  - recaps/96-helical-beginnings.md
  - recaps/97-gnolled.md
  - recaps/98-information-fishing.md
  - recaps/99-brass-banking.md
  - recaps/110-red-team.md
  - recaps/111-prismatic-pyramid.md
  - recaps/112-tesserect.md
  - recaps/113-selune-royale.md
  - recaps/114-familiar-travel.md
  - recaps/115-velddrinnsshark.md
  - recaps/116-wizard-gank.md
  - recaps/117-acro-police.md
  - recaps/118-acid-acropolis.md
  - recaps/119-felgolos-reborn.md
  - recaps/100-backstage-octagon.md
  - recaps/101-leverage.md
  - recaps/102-octagone.md
  - recaps/103-nat1-teleport.md
  - recaps/104-winter-mazelord.md
  - recaps/105-neverwinter-estate.md
  - recaps/106-hydrangeal-planning.md
  - recaps/107-blunt-backstab.md
  - recaps/108-blood-ception.md
  - recaps/109-arklem-oubliette.md
  - recaps/120-liches.md
  - recaps/121-kiaransal-three.md
  - recaps/122-gregorian-planning.md
  - recaps/123-kiansalee-attacks.md
  - recaps/124-kiaransalee-battle.md
  - recaps/125-denouement.md
markdown_extensions:
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break
  - toc:
      permalink: '#' # heading anchor
      slugify: !!python/name:pymdownx.slugs.uslugify
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
  - roamlinks
    #- autolinks
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
copyright: 2018-2021
extra:
  generator: false
  social:
    - icon: fontawesome/regular/bookmark
      link: https://clux.dev
    - icon: fontawesome/brands/github
      link: https://github.com/clux/campaign
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sszynrae
